# Generated by CodiumAI
import os

import pytest

from config_manager.env_var import EnvVar


class TestEnvVar:
    # Tests that the value of an existing environment variable can be retrieved
    def test_get_existing_var(self):
        os.environ["EXISTING_VAR"] = "existing_value"
        env_var = str(EnvVar("EXISTING_VAR", "default_value"))
        assert env_var == "existing_value"

    # Tests that the value of a non-existing environment variable can be retrieved with a default value
    def test_get_non_existing_var_with_default(self):
        env_var = str(EnvVar("NON_EXISTING_VAR", "default_value"))
        assert env_var == "default_value"

    # Tests that the value of an existing environment variable can be set
    def test_set_existing_var(self):
        EnvVar("EXISTING_VAR", "new_value").set()
        assert os.environ["EXISTING_VAR"] == "existing_value"
